name: Azure Function CI/CD

on:
  push:
    branches:
      - main  # Asegúrate que tu rama principal se llame así

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Deploy to Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: lexureappfunc01  # Cambia este nombre si tu App Service se llama distinto
        package: '.'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
